### ISSUE TITLE
Add audio mixing into data model and TTML representation

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#105]
We say surprisingly little at the moment about how to define audio mixing and link in audio resources. It's technically there via the profile definition, but it needs to be added to the data model and the TTML representation so it's clear how to use it.

**Comment by nigelmegitt** [comment]
Planning for this:

- [ ] Add Audio to data model
- [ ] Add Mixing Instruction to data model
- [ ] Define Audio as either an [`<audio>`](https://www.w3.org/TR/ttml2/#embedded-content-vocabulary-audio) with a `src` attribute, as a child of a Text (`<p>`) or a TTS directive on a Text, being [`tta:speak`](https://www.w3.org/TR/ttml2/#audio-style-attribute-speak) or [`tta:pitch`](https://www.w3.org/TR/ttml2/#audio-style-attribute-pitch)
- [ ] `clipBegin` and `clipEnd` to be supported
- [ ] `xml:lang` to be supported? If so, must match `xml:lang` of parent 
- [ ] Define Mixing Instruction as a static value of [`tta:pan`](https://www.w3.org/TR/ttml2/#audio-style-attribute-pan) or [`tta:gain`](https://www.w3.org/TR/ttml2/#audio-style-attribute-gain) or a list of [`<animate>`](https://www.w3.org/TR/ttml2/#animation-vocabulary-animate) elements that vary those attributes (to support `fill="freeze"`) - can be added to Script Events, Texts and Audios.
- [ ] Add examples
- [ ] Add informative explanation of audio mixing semantics - maybe use something like https://w3c.github.io/adpt/#webaudio-section ?
- [ ] Make sure that profile feature requirements are complete and adequate for audio

**Comment by KEEFER82** [comment]
https://www.w3.org/TR/dapt-reqs/#requirements`

**Comment by nigelmegitt** [comment]
@KEEFER82 right, R15 there says:

>A document must be able to reference audio tracks either included as binary data within the document or separately.

Nevertheless, I am interested in implementation experience to guide the related open issues #113, #114 and #115.
