### ISSUE TITLE
Add general type to distinguish Dubbing Scripts and AD Scripts

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#11]
For a DAPT Script, there should be a property to distinguish between Dubbing and AD scripts. At the moment there is a `script type` property that is used for further differentiation (e.g. for Dubbing Scripts into `Original Language Dialogue List`, `Translated Dialogue List` etc.). A processor therefore always needs to "infer" from the sub types the main types. That may cause problems if the list of sub-types is extended.

**Comment by nigelmegitt** [comment]
Editorial issue text from issue 2 in ED: 
>Add script type(s) for audio description workflows. Should the pre-recording/as-recorded scripts be generic?

(noting here because I'm switching the ED text issue to a link to this issue)

**Comment by andreastai** [comment]
I reopened this issue because the original problem has not been addressed yet.

The value "AUDIO_DESCRIPTION" has been added to satisfy https://github.com/w3c/dapt/issues/11#issuecomment-1244151043, but there is still no way to distinguish types for dubbing from audio description types. 

One solution could be a property with two possible values to clarify that a document is for dubbing or audio description. Another option is to prefix all values with "DUBBING" or "AUDIO_DESCRIPTION". For this solution, "ORIGINAL_TRANSCRIPT" and "TRANSLATED_TRANSCRIPT" need to be prefixed.

**Comment by nigelmegitt** [comment]
Thanks @andreastai . I'm having trouble understanding the issue now. Could you give a concrete example of a case where there is ambiguity between the script types now? In particular, does the definition of the subset of script types known as [Dubbing Scripts](https://w3c.github.io/dapt/#dfn-dubbing-scripts) not address the issue?

**Comment by cconcolato** [comment]
So you'd like to call them:
* DUBBING_ORIGINAL_TRANSCRIPT
* DUBBING_TRANSLATED_TRANSCRIPT
* DUBBING_PRE_RECORDING
* DUBBING_AS_RECORDED
* AUDIO_DESCRIPTION
Is that right?

If that's the case, maybe we should have "daptm:applicationType = dubbing | audio_description" and remove the prefix in the names.
That said, I wonder if "PRE_RECORDING" and "AS_RECORDED" couldn't be used for audio descriptions too. Pre-recording would not contain any `<audio>` element, just gain/pan/pitch/rate, while `As-recorded` would contain `<audio>` elements. In fact, I wonder if we shouldn't remove Audio Description from the script type and just add it as an application type.

**Comment by nigelmegitt** [comment]
Separate application types, and changing `DUBBING_PRE_RECORDING` to `PRE_RECORDING` could work, yes. It does make sense to have an audio description script start out as `ORIGINAL_TRANSCRIPT` because that would reflect the language of any textual content that is described, like an in-image newspaper headline for example. Then if a translated audio description script is prepared, it would be a `TRANSLATED_TRANSCRIPT`.

**Comment by andreastai** [comment]
> If that's the case, maybe we should have "daptm:applicationType = dubbing | audio_description" and remove the prefix in the names. That said, I wonder if "PRE_RECORDING" and "AS_RECORDED" couldn't be used for audio descriptions too. 

Thanks @cconcolato! That was exactly what I had in mind. I prefer a solution to have an explicit vocabulary item to distinguish between the two types of application.
