### ISSUE TITLE
Discuss extensibility and backwards compatible behavior

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#110]
We should be clear in v1 what we expected implementations to do in the future when they encounter a v2 document. We could state our goal that vNext will always be backwards-compatible and that old processor would still be able to make something out of a new document.

What should we do with profile designators? add versioning?

**Comment by nigelmegitt** [comment]
Also §5.2 _Foreign_ Elements and Attributes: should we change the word "Foreign", or define what we mean by it? At the moment the text in that section would cover TTML2 or IMSC vocabulary as well as anything defined by anyone else.

**Comment by cconcolato** [comment]
I think we could still say something about how to handle future versions, just to make sure implementations are forward looking and that we can count on this behavior in future editions of the spec.
We could say:
* future versions of this specification will be designed in a way that a document compliant to the new version remains compatible with previous versions
* future versions of this specification may use the processor profile signaling to indicate if the features of the new versions can be ignored or not. 
* for example, if a future version defines different content profile and processor profile designators, e.g. v2, future documents that include v2 features will signal the both the v1 and v2 content profiles. If it is acceptable to discard v2 features (i.e. attributes/elements in the DAPT namespace that are not recognized (not defined in v1), or values of DAPT attributes not defined in v1), then documents should signal a v1 processor profile. If not, documents should use the v2 processor profile.

**Comment by cconcolato** [comment]
> I'm not sure that "acceptable to discard v2 features" is something that a document that uses those features would ever indicate.

It'd be an author choice. If your workflow can only produce v2 but the other end can only consume v1, that could be acceptable?

> Such a document would presumably include the v2 content profile designator?

Yes.

> Would be interested to see how you'd map out all the permutations of feature usage, processor dependency, contentProfiles value and processorProfiles value.

Not sure what you mean. If future versions include all the features of previous versions, the approach described above seems simple.

**Comment by cconcolato** [comment]
We should consider the case of extending the possible attribute values and how to handle that in a future version of the specification.

**Comment by nigelmegitt** [comment]
Informative text added in #216. This does not go as far as explicitly mentioning profile features and extensions, but may be enough to close this issue?
