### ISSUE TITLE
Clarify how to use SSML with DAPT

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#121]
Given the overlap between DAPT and SSML, it would be good to have a clarification on how they relate and can be used together (or not). Section https://w3c.github.io/dapt/#foreign-elements-and-attributes could have an example of "proprietary" metadata mixing SSML and DAPT.

**Comment by cconcolato** [comment]
Can we envisage embedding a profile of SSML instead?

**Comment by nigelmegitt** [comment]
It's https://www.w3.org/TR/spoken-html/ and is a working draft right now.

**Comment by nigelmegitt** [comment]
Key question for us here: exactly how should more advanced SSML be embedded into the DAPT Script?

**Comment by cconcolato** [comment]
Here is an real-world example of SSML:
```
<speak version="1.0" xml:lang="en-us" xmlns="http://www.w3.org/2001/10/synthesis">
    <prosody rate="fast">The boy smiles then backs away from the window. He looks up at a sign above the storefront. It depicts a coiled <phoneme alphabet="ipa" ph="&#712;k&#333;-br&#601;">cobra</phoneme> and the words, &quot;strike like a cobra. Cobra Kai Karate.&quot;</prosody>
</speak>
```
As far as I understand, the prosody part can be represented with `tta:rate` but the `phoneme` part is not currently possible.

**Comment by cconcolato** [comment]
As discussed, because other groups are looking into similar topics, we don't want to jump into a conclusion yet. The proposal is to add a note to the DAPT specification saying something like:
> Part of the vocabulary of DAPT overlaps with SSML. This version of the specification does not specify how SSML can be either generated from DAPT or embedded into DAPT. Future versions of this specification may do so.

**Comment by nigelmegitt** [comment]
One option is to specify a complex mapping to the SSML [`<voice>`](https://www.w3.org/TR/speech-synthesis11/#S3.2.1) element from attributes on `<ttm:agent>`.
