### ISSUE TITLE
Explicit reference to the Related Media Object

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#122]
What is the recommended way to point to the Related Media Object that was used to produce a script? It certainly can be done with proprietary metadata but since it is probably a common need, it might be worth having a standard way to do it.

**Comment by nigelmegitt** [comment]
That's a good idea. We have the same issue in EBU-TT, where the [EBU-TT Metadata spec, Tech3390](https://tech.ebu.ch/publications/tech3390), defines `ebuttm:sourceMediaIdentifier` - I would propose that we reference that somehow. Perhaps in an informative section on additional metadata?
