### ISSUE TITLE
Consider restricting time expressions

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#123]
Given that the time expression syntax for `#time-clock-with-frames` can be misinterpreted as a SMPTE time code, which are not supported, we should consider not permitting `#time-clock-with-frames` and only support `hh:mm:ss.ms` or `f`.

**Comment by nigelmegitt** [comment]
Seems like one to request industry feedback on?

**Comment by andreastai** [comment]
> Given that the time expression syntax for `#time-clock-with-frames` can be misinterpreted as a SMPTE time code, which are not supported, we should consider not permitting `#time-clock-with-frames` and only support `hh:mm:ss.ms` or `f`.

Makes a lot of sense to me:

**Comment by palemieux** [comment]
>  we should consider not permitting #time-clock-with-frames and only support hh:mm:ss.ms or f

+1

**Comment by nigelmegitt** [comment]
I'll open a pull request for this

**Comment by nigelmegitt** [comment]
#127 opened - please review. Prohibits all frame based time expressions.
