### ISSUE TITLE
Reconsidering the role of character styles

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#124]
In my opinion, the use of character styles in the specification has limited practical use. Here are a few reasons why:

- A character style is tied to one character and cannot be applied to a group of characters with similar requirements.

- The application of a character style to a script event or text must be done explicitly, and there is no automatic application based on the character referenced through the `@ttm:agent` attribute.

- The only extra information carried by the application of a character style is that it was authored to be applied to a specific character, which may not justify the introduction of this concept.

Currently, the same effect as a character style could be achieved by using a "regular" style, which would allow for the reuse of style objects.

One possible reason for the current design may be to allow for multiple character styles to be applied to a single character. An example use case where this could be helpful is the application of one character style to the original language text and another character style to the translated text associated with the same character. If this is a use case, providing a code example would help to illustrate this scenario more clearly.

Depending on the supported workflow, it could be useful to allow a many-to-many relationship instead of the current one-to-many relationship. This would allow for one style to be applied to multiple characters. In this case, it may be beneficial to reverse the reference direction so that a character object references zero or many styles instead of a style object referencing one character.

**Comment by cconcolato** [comment]
I think we are trying to solve 2 use cases with styles and that is creating confusion:
1. In some dubbing applications, during the recording of voices, a display shows the text to be spoken by each actor, with a different style for each actor so that they can each easily identify their lines. That was the initial intent of attaching styles to characters. In this case, even if multiple actors speak at the same time the text is displayed multiple times, each time with the specific actor style.
2. In some cases, original language transcripts could be used to produce closed captions/subtitles/forced narratives (e.g. after adjusting for reading speed constraints) and in this case, styles could be applied to events (e.g. voice over being italicized).

I wonder if we shouldn't be more explicit and say that for use case 1, styles can be linked with/embedded in the character definitions but should not be linked to the events. And that linking styles to events (as usually done with the `style` attribute et al.) can be done for use case 2, but is typically out of scope of DAPT.

**Comment by andreastai** [comment]
Thanks, @cconcolato! It's really helpful to see the use case behind character styles. I support your proposed solution. It would result in a cleaner and clearer implementation of Use Case 1.

**Comment by andreastai** [comment]
@nigelmegitt @cconcolato That's how I understand the proposal. I know that is going beyond what TTML currently allows, but from my view, this would better map the relationship between styles and characters.

**Comment by nigelmegitt** [comment]
My initial reaction is that I am extremely reluctant to add more ways to apply styles than the current ones (inline, referenced, and animation), particularly ones that only address a narrow problem space. Especially in v1 of DAPT this is too much.

There may be a different, more wide ranging discussion to be had to allow selector-based styling in TTML though, which would need us to think more about how to transition, and the model for allowing CSS in - if we had a solution like that, I could imagine a `::character` pseudo-selector being a relatively simple addition.

**Comment by andreastai** [comment]
I understand your reluctance, @nigelmegitt. If this feature were introduced in DAPT, a TTML-compliant rendering processor would not be able to handle it.

However, I wonder if the current solution is the best way to address the first use case that @cconcolato described for dubbing applications. It may be worthwhile to consider the steps needed to apply character styles. First, the script is created without defining styles. Once the script is completed, the styles are defined and a reference to an existing ttm:agent element is established. Finally, these styles need to be referenced by all script events that have the corresponding character (if the intent is to apply the character style to all script events for a specific character).

Let's say you make an error and apply the wrong style to a character. You would need to delete the reference to the ttm:agent element from the style element and add a reference to the same `ttm:agent` element to another style element. However, the script events are still associated with the incorrect style reference. As they now reference a regular style, this is not an error and is fully compliant with DAPT. If you apply the new character style to a script event, you won't know if the existing style should be maintained.

I'm sure that the current solution can be implemented, but it may be worth reviewing to see if there is a better way to accomplish this.

**Comment by andreastai** [comment]
@nigelmegitt 
> The way I see it, this is something that can be checked with a validating processor at the moment,

Thanks, I wasn't aware this was the main purpose.

> I would prefer to gain implementation and usage experience before making any stronger normative statements here.

Makes sense to me.

> There's a mechanism that may not at first be obvious, that might be useful, in which a style is defined without a ttm:agent and additional styles are defined that reference that "group" style and each have a different ttm:agent

Thanks! I have forgotten about the option that styles can reference other styles. That is indeed a valid solution. As said before it would be good to get feedback from implementers. I wounder how much referential styling on style elements is currently used.

**Comment by andreastai** [comment]
Thanks for your proposals @nigelmegitt. I need to go through this with some hypothetical examples, and it certainly makes sense to wait for feedback from the wide review as well.
