### ISSUE TITLE
Signaling frame rate

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#146]
The current specification says:
> If the document contains any time expression that uses the f metric, or any time expression that contains a frames component, the ttp:frameRate attribute MUST be present on the `<tt>` element.

It should mention that when frame rate is not an integer, `ttp:frameRateMultiplier` MUST be used.

**Comment by nigelmegitt** [comment]
Sounds like an informative note to me, since the normative requirement for that is already in TTML, if the document needs to use a non-integer frame rate.
