### ISSUE TITLE
Consider identifying the original language on top of the current language

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#148]
For dub scripts, in some cases, the document may not contain anymore the original language (for example after recording). It could still be useful to identify the original language (if only to make it clear that the language is not the original). It could be with a `daptm:originalLang` attribute at the tt level.

**Comment by nigelmegitt** [comment]
The original transcript might not all be in one language, so a tt level attribute might not always work. That would suggest that the script event level is more appropriate.

**Comment by cconcolato** [comment]
> The original transcript might not all be in one language, so a tt level attribute might not always work. That would suggest that the script event level is more appropriate.

Just like `xml:lang` in the `originalTranscript`. The meaning of `daptm:originalLang` would simply be: it represents the value that `xml:lang` had in the `originalTranscript`.

**Comment by nigelmegitt** [comment]
If you want to know the original language, why would you not also want to know what the original language text was? If you keep the original transcript text, then you already know the original language.

A secondary consideration: is it important to distinguish between the source language for each translation?
e.g.:

* Original -> Pivot
* Pivot -> Target
* Original -> Target

In this case the last, direct, translation might be higher value than the one that went via the pivot.

**Comment by nigelmegitt** [comment]
Would we allow `daptm:originalLang` to be present on Text `<p>`s additionally, to indicate the language used as the source for translation of that specific Text?

**Comment by cconcolato** [comment]
In case the source had multiple languages?

**Comment by nigelmegitt** [comment]
Oh, yes, that's one reason. The other is to indicate if the translation was direct from the original language or was from a pivot language intermediate translation.

**Comment by cconcolato** [comment]
We could consider langSrc having 3 values: original, translation (meaning target) and pivot; and documents could have up to 3 paragraphs per event.

**Comment by nigelmegitt** [comment]
I'll work on a pull request for this.

**Comment by nigelmegitt** [comment]
I've brought this change into #179 because it is directly related, and reviewing one pull request to resolve this issue and #173 seems to make sense.
