### ISSUE TITLE
Text associated with a Character

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#149]
The current spec says in https://www.w3.org/TR/dapt/#text:
>A [Text](https://www.w3.org/TR/dapt/#dfn-text) object may be styled and associated with a [Character](https://www.w3.org/TR/dapt/#dfn-character).

I think that is confusing/wrong. The Event is associated with a Character.

**Comment by nigelmegitt** [comment]
Agree - also it should say one or more Characters.

**Comment by cconcolato** [comment]
The Event part already says:
> Zero or more [Character Identifiers](https://w3c.github.io/dapt/#dfn-character-identifier) indicating the [Characters](https://w3c.github.io/dapt/#dfn-character) involved in this [Script Event](https://w3c.github.io/dapt/#dfn-script-event).

So I think we just need to remove "and associated with a [Character](https://www.w3.org/TR/dapt/#dfn-character)." from the sentence about the Text object.
