### ISSUE TITLE
Paragraph order

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#150]
The spec says in a NOTE
> Within a `<div>` representing a [Script Event](https://www.w3.org/TR/dapt/#dfn-script-event) the order of `<p>` children is significant.

Why is it significant? I think the note needs to say more.

**Comment by nigelmegitt** [comment]
I can't recall how this note came about - I agree it's a strange thing to say in isolation. Unless we can remember what we meant, I'd suggest deleting the note.

**Comment by nigelmegitt** [comment]
I traced the wording back to https://github.com/w3c/dapt/commit/2dddb1051974e4e1286e4a694785915b8939a009 which later got tweaked by #76. This was related to a mechanism for identifying "main" vs "contextual" text that has since been changed significantly. Agree we should remove.
