### ISSUE TITLE
DAPT Data Model: Make `Text` and `Contextual Text` objects

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#16]
The properties `Text` and `Contextual Text` have further properties. It makes sense to declare them as objects.

**Comment by nigelmegitt** [comment]
Not only that, but they are basically the same class. The only apparent constraint is that their languages are different. There should be two properties, that both have the same class of object as their value, with this constraint applied in the referencing text.

**Comment by nigelmegitt** [comment]
I believe this is done in the current ED, if you want to confirm that we've understood, @andreastai ?

**Comment by andreastai** [comment]
As `Contextual Text` does not exist anymore and `Text` is now an object, this looks good to me. Thanks!
