### ISSUE TITLE
How can mixed direction ltr and rtl be specified in metadata elements

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#164]
If a user needs to mix rtl and ltr content inside a metadata element such as `ttm:desc` there appears to be no way to do that right now. How can it be added?

The TTML2 elements that specify `Content: #PCDATA` that contain human readable text are:
* `ttm:copyright`
* `ttm:desc`
* `ttm:item`
* `ttm:name`
* `ttm:title`

None of these appear to contain a mechanism for marking up mixed direction, though the control codes could in principle be used.

**Comment by nigelmegitt** [comment]
I had the opportunity to look at how an authoring tool supplier puts human-written notes into documents today, and they just used XML comments. We tried a mixed RTL and LTR script comment and I think it just used the Unicode direction control codes.

**Comment by nigelmegitt** [comment]
https://www.w3.org/TR/international-specs/#bidi_inline_change suggests that requiring support for Unicode control characters is an adequate mitigation here. We should explicitly state that it must be required.

**Comment by andreastai** [comment]
This seems to be the only solution at the moment. In retrospect, it appears to be a failure not to allow markup in these metadata elements.

**Comment by nigelmegitt** [comment]
I agree @andreastai - I think for the time being we should mention the need for control codes, and in the future we should consider adding directionality markup within metadata elements. It will not render any current solution invalid if we do that.
