### ISSUE TITLE
Make comment on the end time of a DAPT Script a separate bullet point

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#171]
In the last note of Section [4.1.6.1 Timing Properties](https://w3c.github.io/dapt/#timing-properties), in the second bullet point that comments on the use of the End property, it is stated: 

> The end time of a DAPT Script is for practical purposes the end of the Related Media Object.

 This sentence should be a separate bullet point in the note and should come after the bullet point discussing the Duration property, as it applies to both the End and the Duration property.

**Comment by nigelmegitt** [comment]
Included in pull request #207, open for review.
