### ISSUE TITLE
Change order of descriptions of Character and Talent Name property

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#172]
Reconsider the order of the bullet points that define the structure and constraints of the Character in Section [4.2](https://w3c.github.io/dapt/#character). For better readability and understandability, put the bullet point about the structure of the Character before the bullet point about the Talent name property. Logically, the Talent name builds upon the description of the Character.

**Comment by nigelmegitt** [comment]
Pull request #211 open for review.
