### ISSUE TITLE
Use of the value "Original" for Text Language Source when it refers to non-dialogue sound

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#173]
In Section [4.5](https://w3c.github.io/dapt/#text-language-source), it is stated that the value `Original` for the Text Language Source property could be used in case the associated content is a

> representative of non-dialogue sound and is in the Primary Language of the DAPT Script.

If, in a translation, the original text is preserved as shown in [Example 9](https://w3c.github.io/dapt/#example-9), it would then not be possible to include a French description of the non-dialogue sound of the (original) French transcript.

**Comment by nigelmegitt** [comment]
Sorry, I don't understand here @andreastai . Did we accidentally prevent there being an `original` text language source Text for the retained original language (French in this case) non-dialogue sound when there are translations present?

**Comment by andreastai** [comment]
> Sorry, I don't understand here @andreastai . Did we accidentally prevent there being an original text language source Text for the retained original language (French in this case) non-dialogue sound when there are translations present?

@nigelmegitt I think so. How would you distinguish in Example 9 the description of the non-dialogue sound in French that was kept from the transcript from the non-dialogue sound in English (that may be the translation of the former)? As the English description is in the Primary Language of the DAPT Script, the value of the Text Language Source should be `Original`.

**Comment by nigelmegitt** [comment]
Ah, I see, thank you. To help future me remember how to work out this is a problem:

1. Primary Language can be the Original language or a Translation language.
2. Text that is labelled as Original language and is representative of non-dialogue sound apparently has to be in the Primary language. But if the Primary language is a Translation language, then we should not be calling that Text "Original language".

I'll try to craft an edit that allows for all the possible scenarios.

**Comment by andreastai** [comment]
Thanks @nigelmegitt!

> Text that is labelled as Original language and is representative of non-dialogue sound apparently has to be in the Primary language.

I am not sure if this is so obvious. DAPT can also be used to produce SDH (subtitles for d/Deaf and hard of hearing). If a transcript was produced in the original language and is then translated, the non-dialogue sound that was described in the original language may be also labelled as "Original".

**Comment by nigelmegitt** [comment]
Yes, it's the interaction with Primary language that's the problem, I think. The primary language can change, but that's not supposed to change whether Text is in the original or a translated language.

**Comment by nigelmegitt** [comment]
Looking at this, it seems that we have the same problem for descriptions of the scene (i.e. audio descriptions) too:
>* representative of the scene in the original programme video, and is in the Primary Language of the DAPT Script.

Given that a usage pattern may be to translate the audio description, so that it can be provided alongside a dubbed version, it seems to me that original language descriptions need to be in the same language as the original programme audio, so that a translated audio description can be marked as being a translation. Fixing this would breaks the linkage between text language source and Primary Language in all cases, which I'm coming round to thinking would be a Good Thing.

**Comment by nigelmegitt** [comment]
@andreastai please could you review #179 to see if it addresses the issues here, and doesn't introduce (too many) new ones? I've tried to remove the dependency between language source and primary language to remove the issue around translations of non-dialogue sounds and audio descriptions.

**Comment by nigelmegitt** [comment]
Thanks for reviewing @andreastai - you may well be right, but I think the issue you raised here was significant enough to make it worth while to (possibly) create and then resolve those issues rather than leave it as it was.

**Comment by nigelmegitt** [comment]
I think the discussion above is largely sidestepped by the change just made to #179 in line with the discussion at #148, which is to allow `daptm:langSrc` to be omitted for non-translated content, and for translated content, to have it specify the source language for the translation.

I'd welcome any feedback to either confirm this or show me where the remaining problems lie!
