### ISSUE TITLE
Consider removal of distinction between script and transcript in chapter 2.1

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#175]
The distinction between script and transcript in [chapter 2.1](https://w3c.github.io/dapt/#transcripts-and-scripts) is confusing. While script is used here for differentiation, the term 'script,' in combination with the type of domain or workflow, is used as a superset. Thus, a DAPT script or a Dubbing script can be both a script and a transcript. It is worth considering whether the differentiation in 2.1 is redundant since the ScriptType values already sufficiently differentiate various script types.

**Comment by nigelmegitt** [comment]
See also #169 which is perhaps tangentially related.

Looking at this, we don't use the term "script" alone to mean either a transcript or a script, we only use "DAPT Script" or dubbing script. Arguably, "dubbing script" should be defined in terms of "DAPT Script", but I'm not sure that would make much difference, practically.

@andreastai do you have in mind an alternative wording to replace the shorthand of "script" being either a pre-recording script or a transcript?

I think the job that §2.1 is trying to do is introducing the problem space and the terminology being used within it. Unless we replace "DAPT script" with "DAPT transcript or script" everywhere, and do the same for dubbing script, or find another term that is the superset of "transcript" and "script" I'm not sure how to improve this.

**Comment by andreastai** [comment]
@nigelmegitt To use "script" as a superset for pre-recording script or transcript is ok. But I think it should then not be used as a term that separate a type of document from a "transcript" as in:

> In dubbing workflows, a [transcript](https://w3c.github.io/dapt/#dfn-transcript) is generated and translated to create a [script](https://w3c.github.io/dapt/#dfn-script).

**Comment by nigelmegitt** [comment]
I think I don't agree that "script" on its own is used as a superset - is it not always part of a defined term like "DAPT script" or "dubbing script"?

If we used "pre-recording script" as you suggest @andreastai then we would be introducing a different point of confusion because we have a `scriptType` value of `preRecording`.
