### ISSUE TITLE
Audio Mixing Instructions - PS4

### ISSUE THREAD

**Issue by btsimonh** [w3c/dapt#18]
In the requirements document, PS4 is stated as 'for AD only';  I think we should include another workflow 'voiceover' to include multi-role voiceover, where PS4 is equally applicable.

In terms of Stellar usage, we are seeing increasing requirements for 'voice over', indeed with multiple talent voicing and mixing over original voiced material.  This is mainly for lower budget films where the original filming did not allow for separate stems.

This type of use is effectively dubbing, but with the mixing aspects, and indeed we've given the ability to turn on fade information in our .strdub format.

**Comment by nigelmegitt** [comment]
That's a really good suggestion. I see that you opened w3c/dapt-reqs#17 @btsimonh , which I agree is the right place to agree it.

**Comment by cconcolato** [comment]
I would suggest closing this issue as the corresponding Requirements issue was created and adressed.

**Comment by nigelmegitt** [comment]
Agree with @cconcolato , closing.
