### ISSUE TITLE
Example 1 mentions styling and layout

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#198]
Given that we removed mentioning of styling and that layout is out of scope, I wonder if it we should not remove the following from Example 1.
```
    <styling>
      <!-- Styling is optional and consists of a set of style elements -->
    </styling>
    <layout>
      <!-- Layout is optional and consists of a set of region elements -->
    </layout>
```

**Comment by nigelmegitt** [comment]
I think it's fine to include in at least one example that those elements can be present and that they're optional. I don't mind which example it's in. Since Example 1 shows the overall document structure, I think we can leave it as is.
