### ISSUE TITLE
Note at top of §4.3 re events needs to be clearer

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#20]
The note at the top of §4.3 Events:
> It does not have to be unique for this [Event](https://w3c.github.io/dapt/#dfn-event). It may be used to identify in a human-readable way one or more [Events](https://w3c.github.io/dapt/#dfn-event) that need to be processed together, e.g. in a batch recording.

is unclear - what is the "It" that does not have to be unique? Is this note in the wrong place?

**Comment by cconcolato** [comment]
Yes, the note is in the wrong place. It is meant to be attached to "Event Description".
