### ISSUE TITLE
Note about association of Event with Character is incomplete

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#200]
The note says:
> While typically, a Script Event corresponds to one single Character, there are cases where multiple characters can be associated with a Script Event. This is when all Characters speak the same text at the same time.

but the specification allows for *Zero or more* Character Identifiers.

I think we should highlight that no character is indicated when the event corresponds to in-image text or to audio descriptions.

**Comment by nigelmegitt** [comment]
Arguably the Character Identifier _could_ be used in an Audio Description script to identify the voice actor who should record each description, but I agree that for transcripts, this would be a good clarification.

**Comment by nigelmegitt** [comment]
Pull request open for review.
