### ISSUE TITLE
Consider improving identification of divs corresponding to script events

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#233]
Based on discussion at https://github.com/w3c/dapt/pull/216#discussion_r1543244343, I think we should have an explicit signal to indicate when a div represents a Script Event.

**Comment by nigelmegitt** [comment]
One option mentioned in yesterday's call was to require `daptm:represents` on `div` elements that are Script Events. See also https://github.com/w3c/dapt/issues/227#issuecomment-2348776405

**Comment by nigelmegitt** [comment]
Thinking more about this, and the current state of #241, I don't think it's a good idea to overload the meaning of `represents` by adding in the semantic of "is a script event". When discussing #241 we decided to make it inheritable, so it is okay to omit the attribute on a Script Event `<div>`.

I'm not convinced that we need to do anything here at all, but if we do need an explicit signal, I would like it to be something else. Maybe a `dt:o="se"` attribute or something else small? I'd prefer to do nothing though.

**Comment by cconcolato** [comment]
> I don't think it's a good idea to overload the meaning of represents by adding in the semantic of "is a script event"

I don't see it as overloading. They mean the same thing to me. Represents is only meaningful on a script event. It's the inheritance model and the compactness/verbosity considerations that make the concept blurry.

I don't like that we depend on xml:id or that xml:id is required. It may be a good practice in some workflows but not in others.  It makes also the algorithm for generating script events from divs awkward in my view.

I don't have an easy solution. I need to think a bit more.

**Comment by nigelmegitt** [comment]
We're not really depending on xml:id, we're just dependent on the `div` not containing another `div`. The only confusion I see is that a `div` that both has no child `div` and has no `xml:id` would _not_ count as a Script Event, because of the requirement, but in that case, what is it? And how bad is it that there's this weird escape route?

**Comment by nigelmegitt** [comment]
Discussed in TTWG meeting 2024-09-27, agreed to close with no action; can re-open if implementation experience shows this is needed.
