### ISSUE TITLE
Clarify which TTML2 document type a DAPT Script is

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#234]
TTML2 defines 3 [document types](https://www.w3.org/TR/ttml2/#doctypes) but we currently do not say that a DAPT Script fulfils the requirements of a [TTML Content Document Type](https://www.w3.org/TR/ttml2/#ttml-content-doctype).

It may also help readers if we are explicit that a DAPT Script is represented by a TTML document's `<tt>` element, which is only implied at the moment.

**Comment by cconcolato** [comment]
This feels also related to https://w3c.github.io/dapt/#other-ttml2-profile-vocabulary. It says support by DAPT processor is not required but permitted. I think we need to say that vocabulary is not permitted in a DAPT document.

**Comment by nigelmegitt** [comment]
>I think we need to say that vocabulary is not permitted in a DAPT document.

I think that's a separate issue. Our current position is "you can put it in, but don't expect DAPT processors to do anything with it" which I think is fine - it means if people have specific processors that use it, they can.

Also, the set of TTML features we mark as prohibited is really tightly curated, and I don't think this vocabulary should meet the criteria for being prohibited. In general our approach is to allow stuff that isn't actively harmful to DAPT use cases, and I think that applies here too.
