### ISSUE TITLE
ttm:role values - we should be able to define new ones in the registry

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#24]
TTML2 uses a Registry for ttm:role values - we should be able to define new values in that registry without the `X-` prefix, in DAPT, since it's a W3C TTWG spec.

**Comment by cconcolato** [comment]
`x-` was a placeholder until we had this conversation. I would indeed prefer being able to get rid of `x-`. But I wouldn't want to have to update TTML2 to be able to publish DAPT. Additionally, at some point, other possibility was to use/extend https://www.ebu.ch/metadata/cs/EBU-TTContentTypeCS.xml. Any opinion on that?

**Comment by nigelmegitt** [comment]
Oh good reminder, that does actually look like a good source, and value set. If we are using that then I think we need to use a different attribute than `xml:role`. Perhaps this is an opportunity to use [`ttm:item`](https://www.w3.org/TR/ttml2/#metadata-vocabulary-item)?

**Comment by nigelmegitt** [comment]
Yes, sorry, typo, I meant `ttm:role`.

It would make sense to let the registry be authoritative for TTML2, I agree.

Expanding the EBU vocabulary is probably just a request to the EBU Timed Text group, discussion in a meeting (once every two weeks usually) and then upload of the new version: I don't expect it to be difficult or time consuming to do.

**Comment by nigelmegitt** [comment]
We possibly have too many issues on this specific question!

See also w3c/ttml2#1248
