### ISSUE TITLE
Non-Normative Section 6.4 contains normative keyword

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#249]
>   Implementations MUST compute attribute values based on the contents of the 
document instance before applying those computed values to  DAPT data model objects.

This may be derived by TTML2 but it is still not defined as such in TTML2.

**Comment by nigelmegitt** [comment]
Thanks @andreastai , just to check, is the issue here the use of the normative keyword MUST, or is it that TTML2 does not normatively define the semantics being referenced?

**Comment by andreastai** [comment]
It is the use of the keyword MUST. The reference to TTML2 was only mentioned because of the addition 

> "Some normative provisions relating to this section are defined in [[TTML2](https://w3c.github.io/dapt/#bib-ttml2)]."

at the beginning of the section (in case this was the reasoning to use the keyword.

**Comment by nigelmegitt** [comment]
There's a normative reference to this section from §5.2.1:

>After [attribute value computation](https://www.w3.org/TR/dapt/#using-computed-attribute-values), a [presentation processor](https://www.w3.org/TR/ttml2/#terms-presentation-processor) SHOULD ignore [unrecognised vocabulary](https://www.w3.org/TR/dapt/#dfn-unrecognised-vocabulary).

so I will propose a fix for this that makes §6.4 normative, and removes the reference to normative provisions from TTML2 at the top which will no longer be needed.
