### ISSUE TITLE
Attributes with no namespace prefix are not in a global namespace

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#250]
Section 3 states:

> When referring to an [XML] attribute in the prose, the attribute name is given with its prefix, or without a prefix if the
 attribute is in the global namespace.

As far as I know, attributes that are not namespace-qualified are local to the element where they are specified on. They are not in a global namespace but in a "null namespace" or "unnamed namespace".

**Comment by nigelmegitt** [comment]
The specification for this is Namespaces in XML [§6.2 Namespace Defaulting](https://www.w3.org/TR/xml-names/#defaulting) which says:

>A default namespace declaration applies to all unprefixed element names within its scope. Default namespace declarations do not apply directly to attribute names; **the interpretation of unprefixed attributes is determined by the element on which they appear**. 
>
>If there is a default namespace declaration in scope, the [expanded name](https://www.w3.org/TR/xml-names/#dt-expname) corresponding to an unprefixed element name has the URI of the [default namespace](https://www.w3.org/TR/xml-names/#dt-defaultNS) as its [namespace name](https://www.w3.org/TR/xml-names/#dt-NSName). If there is no default namespace declaration in scope, the namespace name has no value. **The namespace name for an unprefixed attribute name always has no value.** In all cases, the [local name](https://www.w3.org/TR/xml-names/#dt-localname) is [local part](https://www.w3.org/TR/xml-names/#NT-LocalPart) (which is of course the same as the unprefixed name itself).

(my emphasis applied)

I agree this is not the same as the "global" namespace, and will propose an edit.
