### ISSUE TITLE
Add profile constraints expressed as features

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#26]
Since we are defining a profile of TTML2 we need to list the permitted/required/prohibited/optional features from TTML2 and those defined locally in DAPT in the conformance constraints. For example see https://w3c.github.io/adpt/#features-section and https://www.w3.org/TR/ttml-imsc1.2/#supported-features-and-extensions

**Comment by cconcolato** [comment]
Yes, I wanted to avoid doing that and reuse IMSC but based on #5, we probably don't have a choice.

**Comment by nigelmegitt** [comment]
Agreed, I think we have to do it. Why did you want to avoid it?

**Comment by cconcolato** [comment]
I did not want to define yet another set of restrictions.

**Comment by nigelmegitt** [comment]
I think we should adopt the text from ADPT's profile [Constraints](https://w3c.github.io/adpt/#profile-constraints) and then modify as needed. This will also bring us more closely into alignment with the editing approach of IMSC and include important requirements like document encoding.
