### ISSUE TITLE
Requirement to support TTML styling of a presentation processor

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt#263]
At the moment a presentation processor must support some TTML styling. Discussing if other presentation mechanisms would also be allowed may be worthwhile. For example, a processor may translate a DAPT document to WebVTT so that a web browser can render it. In this case, the disposition of the styling features (#styling, styling-chained etc.) should be optional.

If the current semantics are kept,  the following statement in the note of section 7.2 should be re-considered for clarification:

>  A presentation processor can also support additional rendering features from TTML2, such as styles for DAPT documents that use that.

In fact (at the moment) a presentation processor MUST support some sort of TTML2 styling.

**Comment by nigelmegitt** [comment]
>In fact (at the moment) a presentation processor MUST support some sort of TTML2 styling.

What's the basis for this? I can't see it in TTML2, so I'm not sure where this comes from. Regardless, there are audio styling features for which processor support is required, so I think the requirement is actually met.

I think it's arguable whether a translation of DAPT into WebVTT is a presentation process or a transformation one, since WebVTT is not in itself a presentation.

**Comment by nigelmegitt** [comment]
My thinking on this right now is to close with no spec change, but I'm not sure I've fully understood your point @andreastai .

**Comment by andreastai** [comment]
>> In fact (at the moment) a presentation processor MUST support some sort of TTML2 styling.

> What's the basis for this? I can't see it in TTML2, so I'm not sure where this comes from. 

The following feature are all marked as permitted and are therefore required for a transformation and a presentation processor.

* #styling-chained
* #styling-inheritance-content
* #styling-inline  
* #styling-referential

**Comment by nigelmegitt** [comment]
@andreastai I don't see any requirement to support specific styling features in those 4 feature definitions; rather they are all about how processors support different ways in which styling can be applied, if it is present.

The features that do require support for style attributes, that are already required, are:

* #gain
* #pan
* #pitch
* #speak

Would an improvement to the wording resolve this issue, e.g. change:

>A [presentation processor](https://www.w3.org/TR/ttml2/#terms-presentation-processor) can also support additional rendering features from TTML2, such as styles for DAPT documents that use that.

to something like:

>A [presentation processor](https://www.w3.org/TR/ttml2/#terms-presentation-processor) can also support additional rendering features that are not required by DAPT, for example those supporting visual styling attributes from TTML2 or IMSC.

?

**Comment by nigelmegitt** [comment]
Thanks @andreastai , if you are happy to approve #270 I will merge it quickly, since it's a purely editorial change.
