### ISSUE TITLE
Specify that user-defined values can be used for features other than daptm:represents and daptm:scriptRepresents

### ISSUE THREAD

**Issue by ssunkavelli19** [w3c/dapt#271]
Right now, the spec mentions that user-defined values are permitted for `daptm:represents` and `daptm:scriptRepresents` with the `x-` prefix. Can we make sure this is specified for the `daptm:descType` registry values and other registry tables where we'd like to permit user-defined values?

cc @cconcolato for visibility

**Comment by nigelmegitt** [comment]
Sorry I missed this - it would be a substantive change too, I _think_.

I don't have any objections to it. There are only two Registries in DAPT at the moment.

**Comment by nigelmegitt** [comment]
Additionally, I see that we don't have any extension feature for `daptm:descType`. There's no behaviour associated with it semantically, but there should be an extension feature because implementations need to recognise it syntactically.

I'm happy to draft a pull request adding both things.

**Comment by nigelmegitt** [comment]
#278 opened to address this issue. Since it's a substantive change, it would be good to get early review and ensure we can merge as soon as the 2 week decision review period concludes.
