### ISSUE TITLE
Example 3 use of "visual.text" is not described

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#276]
Looking at Example 3, `scriptRepresents` uses `visual.text` but no events use it. This is not wrong per se, but a) it's not documented and b) it makes it hard to understand why `langSrc` is empty (presumably if there was text, then there would be an inherent language).

There are 2 options:
- remove `visual.text`
- add an explanation on why`visual.text` is used

**Comment by nigelmegitt** [comment]
Good catch!

Pull request #277 opened to address this, if you want to take a look @cconcolato .
