### ISSUE TITLE
[ED issue] should we define ttm:role attribute values in this specification?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#32]
Was ED Issue text:
>Should these values be defined in this specification? Or should we reuse/extend existing specifications?

See also #24

**Comment by nigelmegitt** [comment]
See also w3c/ttml2#1248

**Comment by nigelmegitt** [comment]
Editors call: agreed to come back to this later.

**Comment by cconcolato** [comment]
For the moment, we keep defining values in this specification. We'll decide later if we move them to TTML2 or a registry.
