### ISSUE TITLE
[ED Issue] Should we use `ttm:role` values for the on screen property?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#34]
From ED Issue under Document Structure -> Event:
>Should we use a ttm:role attribute for that instead?

**Comment by nigelmegitt** [comment]
See also w3c/ttml2#1248

**Comment by cconcolato** [comment]
I don't have a strong preference: either defining a new role value (through the registry or not) or defining a DAPT-specific attribute.

**Comment by nigelmegitt** [comment]
Editors call: agreed to close without further action.
