### ISSUE TITLE
[ED Issue] How to add event type information?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#35]
From ED Issue under Document Structure -> Event -> `ttm:desc`:
>How to add [Event type](https://w3c.github.io/dapt/#dfn-event-type) information? ttm:role? What if already used by the onscreen annotation?

**Comment by cconcolato** [comment]
Options are:
* using one or more `ttm:desc` elements on the div or p with differentiating attributes such at `ttm:role`
* using differently named attributes in a daptm namespace
* using `metadata` element with any child element in a different namespace

**Comment by cconcolato** [comment]
Noting that `ttm:role` is not explicitly permitted on `ttm:desc`, so we might prefer a `daptm:descType` or equivalent.
