### ISSUE TITLE
[ED issue] Consider synchronization and relationship to audio/video programme

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#45]
The DAPT requirements document illustrates that workflows start with an audio/video asset. We should identify if anything needs to be said about any synchronization issues (e.g. as done in IMSC) and if the presence of a "Related Media Object" is always assumed.

**Comment by btsimonh** [comment]
Imagine creating a timed descriptive for a museum.
Although there is no video element, there is still an assumed timeline; an ethereal 'media object'.

Another 'alternative' real-world usage is in the description (even dub?) of live plays/opera, where the presentation is almost always played complete, yet the synchronisation may vary.  But this may be best dealt with by assuming a linear timeline, yet using a non-linear (even discontinuous) one at 'playout'.

**Comment by btsimonh** [comment]
reviewing the PR...  the use of 'intermediate synchronic document' scares me.
I'm not sure we should encourage chopping up the presentation into ISDs (single list of non-conflicting time delimited chunks), as in the real world, we would not want to present a single audio which crossed two ISDs chunk as two separate parts, which using ISDs would encourage?
Probably better to process each audio presentation in parallel, and specify a maximum number capability.
BUT.  note my comments about fade info being separate from audio info (in dapt-req here: https://github.com/w3c/dapt-reqs/issues/21 ).
Maybe we need a totally different intermediate form?  One with a timed stream of audio presentations and program audio modification blocks which are allowed to overlap?

**Comment by nigelmegitt** [comment]
It may be that we don't actually need the synchronisation section at all. If we do have it, in this domain the synchronisation must surely be relative to some related media object that is _audio_ not video (could be the audio component of a video of course).

**Comment by btsimonh** [comment]
@nigelmegitt - audio in the case of dub/vo, but for AD, the video is the important association!

Not sure if you have considered 'Extended AD' - where the AD presentation of the original media may cause the original media to pause at certain points for the AD to complete before playing again.
https://www.w3.org/TR/WCAG20-TECHS/G8.html#:~:text=Extended%20audio%20description%20temporarily%20pauses,are%20insufficient%20for%20adequate%20description.

If not, then it's probably a DAPT wishlist item, as I'm not aware of good examples of preparing such a thing at the moment.
It's not something we've implemented yet - A method of representing it is evading me so far (although I've not thought too hard yet).

**Comment by nigelmegitt** [comment]
> Extended AD

Raised as #45, let's try to keep it orthogonal to this issue, which is about base level synchronisation, understanding the timestamps and how they relate to some media.

**Comment by nigelmegitt** [comment]
Having reviewed TTML2, there are 2 areas we should be concerned with: time expression relation to media, and any thresholds for synchronisation accuracy.

### Time expression relationship to media

1. I think we agreed to specify that only `ttp:timeBase="media"` is permitted.
2. Then, as per [TTML2](https://www.w3.org/TR/ttml2/#parameter-attribute-timeBase), we should  state that when mixing audio, the media time must begin at (i.e. the epoch is set to) the same time as the audio tracks in the related media, and time elapses according to the play rate of those audio tracks. It may be useful in some applications to use a standalone media timing reference (for example, this is an option with MIDI).

### Synchronisation thresholds

This is trickier. Clearly, accurate synchronisation is somewhat important, for both dubbing and audio description. But _how_ accurate is hard to state. I've asked my colleagues if there's an industry norm we can reference, or similar.

By way of research, the control signal for MIDI appears to go down to quarter of a frame, presumably at 30fps, which is around 8.3ms. This may be misleading though: I'm not a MIDI expert, and reading up on it, there also seems to be the concept of a "tick rate" which is dependent on the time signature, itself related to the "beats per minute" of the music, which seems not relevant in our use case.

Lip-sync accuracy thresholds are probably relevant for dubbing mixes; it may be a general expectation right now that dubbing mixes will be done as a separate activity from DAPT script production, but this may not remain true. It is easy to imagine that a dubbing workstation would use the times within the dubbing script (after adaptation) to produce the final mix.

Right now my assumption is that we do need say _something_ about synchronisation accuracy, but more research is needed to understand what!

**Comment by btsimonh** [comment]
Summary:
my vote is +- 20ms, if there needs to be a recommendation.  But, I would expect systems to perform to 1ms after the adaptation stage.

Personal perspective:
Scripting mechanisms will always almost be based on extant media tools, and work in terms of frames of video.
However, we have a second offset involved here, which is the audio start time and offset into audio.
For me, the 'div' would be timed probably to frame 'resolution'.  i.e. softwares *may* quantise the value according to the video framerate.  This leads to a possible 'jitter' of +-~20ms (assuming 23.976 is the slowest framerate we may encounter) in the scripting.
The Adaptation is free form in terms of the span start point reference to the div - no specific relationship to the frames.
The Audio time again free form with reference to the div.
One would hope that the Adaptation and Recording would be done against a good quality proxy in the same framerate as the master, and so jitter in the scripting is of less importance, happening before we get to the important parts in terms of final timing.

Personally I believe that DAPT would benefit from restricting the representation of time.  I like HH:MM:SS.TTT, but at the end of the day it does not matter which as long as it's NOT frame based.  i.e. S.TTT is fine also, and most appropriate for values offset from the 'div'.
The reasoning behind this is that calculation from frames is simply not required when you can resolve down to the ms, which is by far good enough resolution for everything we're trying to represent.  Tying anything to frames kind of makes assumptions about video conversion which we don't want to make.  MANY of my customers receive one version of a video at 23.976, and then another at 25 later, and there is no rhyme nor reason in the video timeline duration (or not that such customers can easily understand or predict).

Having said that frames are NOT important, customers do like to have framerate defined - but it's only relevance should be to qualify what FPS the file was created against, and could be an indicator of expected quantisation.

About start time:
All the customers I know wish to relate their files to TimeCode.
i.e. time from start of file is meaningless unless you know where the file starts in the media, and they do not want to get this from external systems.
In IMSC-Rosetta, we made the time values HH:MM:SS.TTT as a *real time* representation of the timecode, so retaining the link to specific media TC, whilst *not* using timecode itself.  This was in the absence of a decent, easily findable representation of the original media start TC.  I'd be happy with 'media time starting at zero' if there was a defined mapping of media timecode to the file zero.

**Comment by nigelmegitt** [comment]
> Personally I believe that DAPT would benefit from restricting the representation of time. I like HH:MM:SS.TTT, but at the end of the day it does not matter which as long as it's NOT frame based. i.e. S.TTT is fine also, and most appropriate for values offset from the 'div'.

This comment is relevant to #59.

**Comment by nigelmegitt** [comment]
> I'd be happy with 'media time starting at zero' if there was a defined mapping of media timecode to the file zero.

That is already the case in TTML, for file based media. For streams, time zero is the same as the epoch that the stream times relate to, which is arbitrary but defined at the point of usage.

**Comment by nigelmegitt** [comment]
> This leads to a possible 'jitter' of +-~20ms (assuming 23.976 is the slowest framerate we may encounter) in the scripting.

That's interesting, and I _think_ orthogonal to this issue, but I can see that there could be a relationship. Whereas you're pointing to timing errors introduced by quantisation to frame boundaries at _authoring_ time, my intent was to specify the synchronisation accuracy at _presentation_ time, based on whatever computed times arise from the document as authored.

By presentation time I mean the point in the workflow where audio mixing happens.

I do think that whatever presentation time synchronisation thresholds we require could have an impact back onto authoring systems and practices.

**Comment by btsimonh** [comment]
Ahh, ok, understood.
Offline mixing should perform to ms accuracy to the numbers in the file.
If the mixing is being done at the point of presentation, then I believe ms timing to be *achievable* but possibly difficult.
e.g. audio can be accurately scheduled, as can audio modification (fades).  If these items are scheduled by reading the current time of playing media, and then scheduled for an exact moment in the future, webaudio (for example) should be completely competent at achieving the accuracy with pre-loaded audio snippets, as long as the media is in 'play'.
If triggered in 'real time' from events, the accuracy will be variable, especially under load.  (e.g. if a VTT timeline were created from required times, and the triggering of these 'subtitles' used for timing).

If we are considering mixing presentation timing, we should also consider mixing presentation.  e.g. "when presenting an audio snippet, it should fade up over Xms to avoid 'pop' and fade down over Xms".

Q: Is DAPT aimed at being a 'presentable' (i.e. emission) format or as an intermediate format?  The requirements are different?

**Comment by nigelmegitt** [comment]
> If we are considering mixing presentation timing, we should also consider mixing presentation. e.g. "when presenting an audio snippet, it should fade up over Xms to avoid 'pop' and fade down over Xms".

Those are specific examples were computed times would need to be honoured to within whatever threshold we all think is acceptable. The fade values would be set at authoring time by using the `<animate>` element to vary the value of the `tta:gain` attribute value, and the times would be set by defining the `begin` and `end` attributes on that element.

This means that the fade amounts and times are delegated to the authoring tool and whatever guidance is in place locally. That flexibility can be useful in practice, for example it allows for no fade at all if the background audio behind an audio description is so quiet that it can be left un-faded without audience impact.

It seems unnecessary to specify different timing synchronisation thresholds for gain animation than for audio resource playback, but it would not be ideal if a particular implementation had wildly different relative timing for those two features of playback, for example if it began playing back an audio resource 0.3s early and only applied the fade 0.2s late. Not sure if we need to say that though!

>Q: Is DAPT aimed at being a 'presentable' (i.e. emission) format or as an intermediate format? The requirements are different?

Both, in different use cases. So far we haven't identified any requirements that are different or incompatible, but if you notice any, please do raise an issue on w3c/dapt-reqs.

**Comment by btsimonh** [comment]
"mixing presentation. e.g. "when presenting an audio snippet, it should fade up over Xms to avoid 'pop' and fade down over Xms"."
No, I meant fade of the *foreground*, recorded audio to be rendered on top!  If we are defining a presentation, then we must avoid ticks & pops by advising mixing practice - i.e. don't just start an audio at sample 100 which may have a value of 0.6, and not expect a big pop on output.

**Comment by nigelmegitt** [comment]
Hmm, `tta:gain` can be applied to foreground audio as well as "background". Do we need to specify an additional implementation requirement?

**Comment by btsimonh** [comment]
I think pop prevention is not something that should be scripted in the file, but just noted as an observation about mixing.
I can't imagine a file where every presented audio had to have gain animation at start and end to do this job :).
Good to know that ttm:gain can be applied to foreground - as I use all our audio non-destructively, so as a minimum, I would use a single non-animated gain value.

**Comment by nigelmegitt** [comment]
Pull request #120 opened. I went for a SHOULD against 10ms accuracy in time constrained applications, as a "line in the sand". Could be changed if not appropriate.
