### ISSUE TITLE
[ED issue] Consider a different use of features

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#47]
Defining a specification based on Features is a good thing, if only for generating test vectors, implementation report ... IMSC defines its profile based on TTML2 features and also defines its own features also in terms of elements attributes. I find it complex for DAPT specification readers or implementors who are not experts in the TTML2 specification. 
It should be possible to define DAPT features, based on use cases, implementation capabilities ... (e.g. capability to have "Characters", to treat Styles, to treat multiple languages, to render audio ...). 
If a formal definition of a profile in terms of TTML2 features (i.e. use of `#`) is required, it should be done in an Annex.

**Comment by nigelmegitt** [comment]
#103 moves the formal definitions of the profile into an Appendix. If we're happy to merge that, then I think we can close this.
