### ISSUE TITLE
Is the basis for DAPT IMSC 1.1 or is it an independent spec with common provisions?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#5]

**Comment by cconcolato** [comment]
Strictly speaking DAPT does not need to be based on IMSC1.1, but a) it is easy to use it as a basis (many restrictions are the same), b) in some cases you want to have presentation styles for example for presentation in recording systems and c) some of the scripts could be easily transformed into subtitles compliant to IMSC1.1.

**Comment by nigelmegitt** [comment]
I think introducing a formal dependency is going to create more problems than it solves. For example, [IMSC §7](https://www.w3.org/TR/ttml-imsc1.2/#supported-features-and-extensions) explicitly prohibits TTML2 vocabulary that is not listed as permitted, that we will likely want to include. Conversely, requiring DAPT implementations to support all the features of IMSC would be inappropriate because many of the features are not core to DAPT requirements.

If we want a formal link between IMSC and DAPT then we'll have to change IMSC, and that doesn't seem like a good idea. 

Instead I would suggest that we are permissive in allowing DAPT documents to use permitted IMSC features, without requiring implementation support, and provide some guidance about how to transform DAPT scripts into compliant IMSC 1.1.

That guidance could be a separate Note, perhaps.

Also, I recommend we take inspiration from the IMSC specification structure, since that seems to have worked well. I tried to do this with ADPT to some extent.
