### ISSUE TITLE
Real world usage

### ISSUE THREAD

**Issue by btsimonh** [w3c/dapt#50]
The experience with 'designing' IMSC-Rosetta has highlighted that TTML is really too hard for most people to implement well.
It may work as an emission format, but it _does not work for users as an interchange format_.
DAPT is specifically being imagined as an interchange format, and so interoperability is key.

As a 'profile' of TTML, DAPT itself may not be able to constrain things in the same was as IMSC-Rosetta (which is not a profile, but rather a 'file format').

But we _should_ consider simple parsers and implementation simplicity when specifying DAPT.

### **There are things we can look at which make it easier.**
1/ Element order:
e.g. to enable the use of 'simpler' (and faster) parsers, ensure we don't rely on the order of elements with different names.  e.g.
```
<span/>
<br/>
<span/>
```
becomes 
```
{
  "span":[{}, {}],
  "br":[{}]
}
```
in most simple javascript XML parsers.

This was one of the few places in TTML for subtitles which caused a lot of pain and could not be avoided, but was resolved with the odd (but legal) construct
`<span/><span><br/></span><span/>`
If we could consider the requirements for element order in DAPT, and if we can stay with no element order dependency, it would make implementations simpler, and possibly reduce parse time by a factor of 4.

2/ xml:space
Noting that because we're not subtitles, we don't need to represent EVERY space, and have no boxing issues, xml:space can be 'default', and so prettification is ok.  Recognising this would be useful.  (and understanding IF there is any need for preserve in this use case?).  In TTML, xml:space="preserve" is necessary in multi-span with boxed spans - yet this fact is not known to most implementers (gaps between boxed spans may occur).

### **Personally, I would add another document alongside DAPT**,
e.g. DAPT-Impl, which defines a 'File format' fully compatible with DAPT, in the same way as IMSC-Rosetta is fully compatible with IMSC.  This would provide an implementation guideline with simple rules, heavily constrained, yet far easier to implement, and easier to qualify.  As a 'file format' and not a formal specification, it's 'constraints' can be very explicit (i.e. it does not need to follow TTML profiling rules).

The response to IMSC-Rosetta from real users has been extremely positive; almost every user/customer/implementer has complaints over the complexity and variety of TTML, and some refer to TTML and even IMSC as only suitable for "transferring text and timing" when used as an interchange format - so no better than SRT at the end of the day, and SRT is simpler to implement and understand.  Implementing general TTML adds a lot of cost and complexity, and suffocates interoperability.

In IMSC-Rosetta, we explicitly define namespace prefixes, style names, time type, etc., and specify exactly how to achieve common subtitle quality features, so enabling engineers to focus on the subtitles, not on the XML and the TTML, and allowing round-trip conversion in a few lines with no prior knowledge of XML or TTML (using the **most common** javascript library), or having to dig through multiple libraries before you find one which will do the job.  IMSC-Rosetta, although fully IMSC compatible, is not intended as an emission format - we would expect it to be converted before distribution for display/render.

**Comment by cconcolato** [comment]
What is IMSC-Rosetta? Do you have public documentation?

**Comment by btsimonh** [comment]
Hi Cyril, just pinged you an invite to a private repo.  
The repo will be public once we've adjusted based on initial feedback.
Please email your thoughts - simonATyellaumbrella.tv

**Comment by cconcolato** [comment]
I'd rather review public documents.

**Comment by nigelmegitt** [comment]
Our goal is to try to define something clearly enough that there is no need for an additional separate file format document: our editing work is in progress to define the data model and file format together.

I don't think there's any getting away from the fact that this is an XML document. I just raised #51 to prevent entity expansion from being an implementation requirement. However there are plenty of XML parsers that do not exhibit the undesirable behaviour identified in this issue, or offer a mechanism for working around it, such as identifying the element order some other way. That's not a problem with the specification, in my view, it's a problem of implementation choice. It sounds like you might need to raise a bug report against the XML parsing library!

The element order issue cannot be simply resolved in the proposed way because it is an important requirement that foreign namespace vocabulary may be inserted into the document, i.e. extensibility, and we cannot govern the element ordering requirements of such metadata.

>In TTML, xml:space="preserve" is necessary in multi-span with boxed spans - yet this fact is not known to most implementers (gaps between boxed spans may occur).

Please explain "boxed span".

> The response to IMSC-Rosetta ...

Please raise issues with IMSC on the IMSC repo.

**Comment by btsimonh** [comment]
@cconcolato - I will try to let you know when it is public.  Or there is https://github.com/imsc-rosetta/imsc-rosetta-qualify which is public, but you'd be wading through code rather than docs.

**Comment by btsimonh** [comment]
@nigelmegitt  "boxed span": off-topic here except as an example of XML issues we could avoid in DAPT, 
but the simple explanation is:
```
<span backgroundColor="black">black </span>
<span backgroundColor="red">red</span>
```
is different to 
```
<span backgroundColor="black">black</span>
<span backgroundColor="red"> red</span>
```
because XML space collapse when xml:space="default" produces an (undesired) unboxed space in the second case.
I believe the boat sailed on fixing this in TTML many years ago, although there is an argument that it could meaningfully be resolved by pruning 'whitespace only nodes which have peer elements' probably with little effect on extant files.
This effectively means that XML writers for TTML MUST present at least `<p>` on a single line of they are not to affect presented output, regardless of xml:space value, which in effect means every TTML XML writer must be non-standard (not desirable).
Not directly relevant here, as I don't believe an unboxed space will affect DAPT's functionality :).
But the point is made as there could be other things in TTML which prevent writing by an unmodified XML writer, and we have the opportunity with DAPT to attempt to avoid such anomalies.


Ref IMSC/TTML and it's suitability as an interchange format, Pierre is aware of my thoughts; I'd rather wait until we can formally introduce Rosetta, and receive public feedback.


ref element order and 'simple' parsers'.  Again, making DAPT easy to parse and write with commonly used simple parsers could be one goal to encourage adoption and reduce the cost of implementation.  Parsing with retention of element order is possible (with the same parser), but much more complex, takes longer, and uses more resources, and the result is not writable without creating a new custom writer (i.e. with 'simple' parsing in xml2js for example, you can read-modify-write in 3 lines).  If this goal is satisfied by stating 'if using a foreign namespace vocabulary, be aware that the order of differently named peer elements may not be preserved in some implementations', then the goal is satisfied.
Most foreign namespaces will be metadata, and most will not rely on the element order of peer elements of different names.

Yes, it's not a 'specification issue'.  We can create a specification which relies on every part of XML to be parsed and reproduced perfectly.  But if we have the opportunity to place light constraints on the XML usage which make implementation a lot easier (like https://github.com/w3c/dapt/issues/51), it is an important consideration if we want the spec to be successfully adopted.

If I spent 3 long weeks trying to identify a correct way to parse and then reproduce a TTML document, after 35 years software experience, 30 years subtitling experience, and 10 years of TTML spec experience, it means it's too hard.  If we can reduce this pain for people new to the spec, then it benefits everyone?

Remember that DAPT appears to be aimed at interoperability of AD/VO/Dub preparation systems.  Currently that means Yella, Starfish, VoiceCue, and a few selected others.  Some may not WANT interoperability, preferring lock-in with proprietary formats.  Simplicity of implementation at a basic level is one way to make it attractive to implement, and with more web-centric workflows, easy javascript (JSON) compatibility is a huge plus.

**Comment by nigelmegitt** [comment]
Re the whitespace collapsing issue, my recommendation would be not to insert whitespace where you don't want and intend it, i.e. omit the new lines between the span elements.

The specific edge case you mention, where you have a preference about _which_ white space to retain, and which to prune, is somewhat interesting: I think you're suggesting that we specify the application's processing of white space when `xml:space="default"` (the default value), where there is some preference for white space as the first or last character content of explicit `<span>` elements vs anonymous (implied) `<span>` elements.

That would only work if we could assume that for all documents and all authors, character content children of `<p>` elements, considered to be "anonymous spans" in TTML, is somehow less valid and relevant than character content children of explicit spans. I don't believe we can make that assumption.

**Comment by nigelmegitt** [comment]
> If this goal is satisfied by stating 'if using a foreign namespace vocabulary, be aware that the order of differently named peer elements may not be preserved in some implementations', then the goal is satisfied.

To the contrary: if we were to make that statement then we would be imposing an unworkable constraint on any implementations and usage scenarios where extension vocabulary is needed, and where the order is important. That would hobble a core goal of using XML, which is to support extensibility. I for one would not accept that.

**Comment by btsimonh** [comment]
> Re the whitespace collapsing issue, my recommendation would be not to insert whitespace where you don't want and intend it, i.e. omit the new lines between the span elements.

Yes - and insist on "preserve", else any XML processor could prettify and destroy....

> That would only work if we could assume that for all documents and all authors, character content children of `<p>` elements, considered to be "anonymous spans" in TTML, are somehow less valid and relevant than character content children of explicit spans. I don't believe we can make that assumption.

Agreed - the ship sailed, and so every TTML writer software must understand to not prettify inside `<p>` for fear of breaking the display, and hence no 'normal' XML writer can be used out of the box without xml:space="preserve" (if the writer observes this).

It should be noted that 
`<span backgroundColor="black">black </span><span backgroundColor="red">red</span>`
and 
`<span backgroundColor="black">black</span><span backgroundColor="red"> red</span>`
are correctly presented regardless of `xml:space`

**Comment by nigelmegitt** [comment]
I thank @btsimonh for the feedback, but on this occasion I'm going to close the issue with no change.

The request is to define a second parallel specification with further constraints, which in my view would only be necessary if there were a specific problem with the current document as it is. I would want to solve it in the specification rather than create a "sticking plaster" solution.

Speaking for myself, I am not sympathetic to the XML parsing and space preservation "issues". They're both very well defined and implemented correctly in a lot of places. I just spent some time surveying the Javascript XML implementations that are [popular on npm](https://www.npmjs.com/search?q=xml&ranking=popularity), and there certainly are plenty that are incomplete with respect to the XML specification, which is unfortunate. Then again, there are others that do appear to support all of the features needed to parse DAPT. I strongly believe it is not our role to work around the existence of poor XML parsers within DAPT (or IMSC for that matter, referencing IMSC-Rosetta).
