### ISSUE TITLE
[ED issue] Consider using the term document vs document instance

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#57]
We should use the term "document" (meaning an XML Document compliant to TTML) rather than "Document Instance" which is defined in TTML:
> A concrete realization of a [timed text markup language document](https://www.w3.org/TR/2018/REC-ttml2-20181108/#terms-timed-text-markup-language-document), where the concrete form is specific to the context of reference.

with "timed text markup language document" being defined as:
> An abstract document that is purported or confirmed to be a [valid abstract document instance](https://www.w3.org/TR/2018/REC-ttml2-20181108/#terms-valid-abstract-document-instance).

and "valid abstract document instance" being defined as:
> An [abstract document instance](https://www.w3.org/TR/2018/REC-ttml2-20181108/#terms-abstract-document-instance) which has been assessed for validity and found to be valid as defined by [4 Document Types](https://www.w3.org/TR/2018/REC-ttml2-20181108/#doctypes).

and "abstract document instance" being defined as:
> An instance of an abstract data set as represented by a [reduced xml infoset](https://www.w3.org/TR/2018/REC-ttml2-20181108/#terms-reduced-xml-infoset).

**Comment by nigelmegitt** [comment]
I don't see the difference between "document == an XML Document compliant to TTML" and "Document Instance" other than that the latter is more clearly defined, in the end.

I'd suggest that we define "document" with an easily understood non-normative meaning, and a normative meaning that is "A Document Instance conformant to the profile defined in this specification", where Document Instance is as per TTML2.
