### ISSUE TITLE
[ED issue] Consider removing the definition section

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#58]
Terms could be defined the first time they are used and linked when they are used subsequently. We don't really need a definition section. Also, we could let respec generate the index section https://respec.org/docs/#id-index

**Comment by nigelmegitt** [comment]
Happy to let respec generate the index, that's a Good Thing.

As a matter of style I am not dogmatic one way or the other. Sometimes the definition section is a reasonable home for definitions, sometimes it's the place where the term is introduced. If we can introduce all terms in text, I agree, the definition section would no longer be needed.
