### ISSUE TITLE
Should we allow inheritance of xml:lang or require it to be set explicitly?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#62]
I think the minimal formal constraint on `xml:lang` is that there must be a correct computed value, but the text at the moment requires the attribute to be explicitly present on `tt` and on every Text object (i.e. `p` element) which goes beyond what's actually needed. 

Consider permitting implementations to use inheritance for `xml:lang` and omit the attribute when not actually needed.

**Comment by cconcolato** [comment]
I think this is covered by the note in the Text section. The issue can be closed.

**Comment by nigelmegitt** [comment]
Agreed.
