### ISSUE TITLE
Improvements to Character specification section

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#66]
Arising from #49:

* [x] Reword (for grammar) note sentence about how all text content identifies its corresponding language
* [x] Move the constraint on "character" agents having actor children to the element where it applies  (it's currently on the "person" agent)
* [x] Swap the order of agents round so it matches in the spec what it will have to be in the document instance

**Comment by cconcolato** [comment]
@nigelmegitt is this still relevant?

**Comment by nigelmegitt** [comment]
Yes, the second task has not been done. 

Also, looking at this harder, I think we may have the ordering constraints wrong. As you can see in [Example 13](https://w3c.github.io/dapt/#example-13), we have a forward reference from one `agent` to another, whereas if we're saying anything about ordering I'd expect us to require only backwards references, so that a linear (SAX) parser can resolve the references as it goes through the document, and not have to hold "hanging" ones until it has seen what they refer to.

If we change that requirement then the order swap task will be needed too.

**Comment by nigelmegitt** [comment]
Sorting this out turns out to be important for completing work on #103 so I'm going to tackle it there.
