### ISSUE TITLE
Consider if `p` elements may be omitted before any text has been written

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#68]
In the first process step, times are identified without adding any text. I think it is more logical to represent this with an empty `<div>` element than to require an empty `<p>` child of every `<div>` element. Current text requires the empty `<p>`.

**Comment by btsimonh** [comment]
Personally, I find requiring the empty `<p>` to be 'simpler'.
From an implementation perspective, less variety is better.  e.g. if we always require the p, then you don't have to check that the p is there before reading the text.  Which leads to where implementations are rushed and done from samples, if there are always p in samples, and the no-p situation has not been seen and catered for, the (bad) implementation may fail - and this is avoided by always having p.

**Comment by nigelmegitt** [comment]
I should expand on why I think that omitting the `<p>` is "more logical": it's the old difference between defining that there's nothing vs defining that there's something, but it's intentionally empty. In other words, omitting the `<p>` means "we have no text here yet" whereas an empty `<p>` means "we have thought about the text that should go here, and there should be nothing". 

In development terms, you could think of it as being a bit like the python construct of a variable being `None` vs an empty string. They're not equivalent.

If we need to help implementers avoid bad implementations, I'd suggest making sure there are test cases for both missing `<p>` elements and empty ones. Attempting to second-guess all the mistakes that implementers might make seems like an uncompletable task to me, and I would be cautious about attempting it! The only way to avoid bugs is not to implement anything...

**Comment by btsimonh** [comment]
Thankyou Nigel, that's a very good explanation of no-p vs empty-p, and I agree :).  I didn't think about it like that.

**Comment by nigelmegitt** [comment]
The normative change that specifies that omitting `p` elements is acceptable is present in #77. ([PR-Preview link](https://pr-preview.s3.amazonaws.com/w3c/dapt/pull/77.html#script-event))

I'm not sure what additional change would be helpful - @btsimonh are you suggesting that we should explicitly describe the circumstances when _no_ `<p>` should be present and when an _empty_ `<p>` should be present? I am wondering who that helps, and why... 

Also, most of the time, an empty `<p>` would be an odd thing: why would anyone create that, practically speaking?

**Comment by btsimonh** [comment]
I just think that by documenting the thought process around why you may or may not present an empty `<p>` may help people understand intent.
e.g. my initial thought was 'why would we have any difference in the structure', countered by your explanation of what a difference in structure could represent.  My initial thoughts were based on 'having the structure always the same makes it easier for implementers', which I feel is a very important feature of the standard if we want successful wide adoption.

**Comment by nigelmegitt** [comment]
@btsimonh I've opened #106 to add informative text about this - I chose to base it on empty Text objects rather than empty `<p>` elements because I think that's the more appropriate conceptual level.

GitHub won't allow me to invite you to review it but if you could add any comments on the pull request that'd be v helpful. Not sure if it will allow you to submit an uninvited review but that'd be even better, if you can.
