### ISSUE TITLE
Additional character metadata

### ISSUE THREAD

**Issue by btsimonh** [w3c/dapt#74]
Question:
Can the ttml tts:agent reflect things like gender?
Thinking ahead, for MT, gender of the speaker can be useful for improved MT output.
There may be other metadata about a specific character which may impact MT (or be beneficial for MT).

**Comment by nigelmegitt** [comment]
Additional metadata can be added, yes. TTWG has not defined any vocabulary for gender, specifically, but if you want to pull some in from some other namespace, I see no issue with that.

The key question here is if there's a need (especially in the first version) for changing the specification to mention any particular vocabulary specifically?

By MT I assume you mean Machine Translation.

**Comment by nigelmegitt** [comment]
This seems closely related to #31.

**Comment by nigelmegitt** [comment]
I think for supporting this use case we would look to include vocabulary and semantics from SSML, for example the [`voice`](https://www.w3.org/TR/speech-synthesis11/#S3.2.1) element - see #121 . Is there any more to do here?
