### ISSUE TITLE
Document conventions contains redundant text

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#93]
The Document Conventions section contains=:
> All content of this specification that is not explicitly marked as non-normative is considered to be normative. If a section or appendix header contains the expression "non-normative", then the entirety of the section or appendix is considered non-normative.

This is redundant with similar text in the Conformance section. I suggest removing it from this section.

I think we could also move the "Feature" paragraph to the conformance section maybe.

**Comment by nigelmegitt** [comment]
+1 to removing the redundant text.

But the "Feature" paragraph actually _is_ a document convention, so it's in the right place. We could put it under a sub-heading though.
